"""Productized subtitle presets from the 2026 Douyin oral-video research."""

from typing import Any


SUBTITLE_TEMPLATES: dict[str, dict[str, Any]] = {
    "renovation_pitfall_yellow": {
        "name": "装修·避坑警示黄",
        "industry": "装修",
        "description": "强钩子、避坑清单、预算警示",
        "preview_copy": ["这3个装修坑", "千万别踩"],
        "style": {
            "font_size": 64,
            "color": "#FFFFFF",
            "outline_color": "#111111",
            "outline_width": 5,
            "font_family": "Microsoft YaHei",
            "position": "bottom",
            "margin_v": 390,
            "max_chars_per_line": 9,
        },
        "keyword_color": "#FFE23B",
    },
    "renovation_editorial_gray": {
        "name": "装修·设计高级灰",
        "industry": "装修",
        "description": "设计理念、案例讲解、高客单审美",
        "preview_copy": ["高级感不靠堆钱", "靠的是细节"],
        "style": {
            "font_size": 54,
            "color": "#F7F3EA",
            "outline_color": "#232323",
            "outline_width": 2,
            "font_family": "Microsoft YaHei UI",
            "position": "bottom",
            "margin_v": 360,
            "max_chars_per_line": 10,
        },
        "keyword_color": "#D8895B",
    },
    "renovation_inspection_blueprint": {
        "name": "装修·工地验收蓝",
        "industry": "装修",
        "description": "工艺标准、验收步骤、材料参数",
        "preview_copy": ["水电验收", "先看这4点"],
        "style": {
            "font_size": 60,
            "color": "#FFFFFF",
            "outline_color": "#0B2239",
            "outline_width": 4,
            "font_family": "SimHei",
            "position": "bottom",
            "margin_v": 380,
            "max_chars_per_line": 9,
        },
        "keyword_color": "#43B8FF",
    },
    "restaurant_owner_billboard": {
        "name": "餐饮·老板大字报",
        "industry": "餐饮",
        "description": "老板观点、经营反差、加盟避坑",
        "preview_copy": ["菜品好吃", "不等于生意好"],
        "style": {
            "font_size": 68,
            "color": "#FFD82E",
            "outline_color": "#16100A",
            "outline_width": 6,
            "font_family": "SimHei",
            "position": "middle",
            "margin_v": 0,
            "max_chars_per_line": 8,
        },
        "keyword_color": "#FFFFFF",
    },
    "restaurant_price_tag_red": {
        "name": "餐饮·红火价签",
        "industry": "餐饮",
        "description": "团购价格、午市套餐、限时活动",
        "preview_copy": ["工作日午市", "只要29.9元"],
        "style": {
            "font_size": 58,
            "color": "#FFFFFF",
            "outline_color": "#6E130F",
            "outline_width": 2,
            "font_family": "Microsoft YaHei",
            "position": "bottom",
            "margin_v": 370,
            "max_chars_per_line": 9,
        },
        "keyword_color": "#FFE873",
    },
    "restaurant_wok_fire_warm": {
        "name": "餐饮·烟火探店暖白",
        "industry": "餐饮",
        "description": "后厨实拍、老店故事、菜品工艺",
        "preview_copy": ["这口锅气", "才是老店灵魂"],
        "style": {
            "font_size": 56,
            "color": "#FFF8E7",
            "outline_color": "#27160D",
            "outline_width": 4,
            "font_family": "Microsoft YaHei UI",
            "position": "bottom",
            "margin_v": 400,
            "max_chars_per_line": 9,
        },
        "keyword_color": "#FFB547",
    },
    "training_key_conclusion": {
        "name": "培训·重点结论黄",
        "industry": "培训",
        "description": "家庭教育、方法论、反常识结论",
        "preview_copy": ["孩子学不会", "往往不是不努力"],
        "style": {
            "font_size": 60,
            "color": "#FFFFFF",
            "outline_color": "#111111",
            "outline_width": 5,
            "font_family": "Microsoft YaHei",
            "position": "bottom",
            "margin_v": 380,
            "max_chars_per_line": 10,
        },
        "keyword_color": "#FFE042",
    },
    "training_framework_blue": {
        "name": "培训·知识框架蓝",
        "industry": "培训",
        "description": "课程知识点、教师 IP、学习规划",
        "preview_copy": ["提分关键", "是建立知识框架"],
        "style": {
            "font_size": 54,
            "color": "#F8FBFF",
            "outline_color": "#0F2841",
            "outline_width": 3,
            "font_family": "Microsoft YaHei UI",
            "position": "bottom",
            "margin_v": 360,
            "max_chars_per_line": 10,
        },
        "keyword_color": "#59BFFF",
    },
    "sinology_ink_gold": {
        "name": "国学·墨韵雅金",
        "industry": "国学",
        "description": "经典解读、修身智慧、中式美学",
        "preview_copy": ["心若安定", "万事从容"],
        "style": {
            "font_size": 58,
            "color": "#F6E7C7",
            "outline_color": "#1A1712",
            "outline_width": 2,
            "font_family": "SimSun",
            "position": "bottom",
            "margin_v": 390,
            "max_chars_per_line": 8,
        },
        "keyword_color": "#D9B45B",
    },
    "sinology_minimal_vermilion": {
        "name": "国学·留白朱砂",
        "industry": "国学",
        "description": "短句箴言、人物故事、情绪疗愈",
        "preview_copy": ["知止不殆", "可以长久"],
        "style": {
            "font_size": 54,
            "color": "#F8F1E2",
            "outline_color": "#241F19",
            "outline_width": 1,
            "font_family": "KaiTi",
            "position": "bottom",
            "margin_v": 420,
            "max_chars_per_line": 8,
        },
        "keyword_color": "#B6382B",
    },
}


DEFAULT_SUBTITLE_TEMPLATE = "renovation_pitfall_yellow"
